### ISSUE TITLE
Attribute super-class

### ISSUE THREAD

**Issue by mabravo641** [adobe-research/vaw_dataset#1]
Hi,
Thank you for releasing the attribute annotations. A am very interested in the dataset.
Are you also planning to release the superclass list of attributes from the paper (the Class imbalance and Attribute types)?
And could you provide your evaluation code to reproduce your results and use the dataset?

Best,
Maria

**Comment by kushalkafle** [comment]
Added subtypes; We will add evaluation code shortly as well. Please reopen the issue if not resolved soon!
